{
  description = "A test flake";

  inputs = {
    flake-utils.url = "github:numtide/flake-utils";
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
  };

  outputs = { self, flake-utils, nixpkgs }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; };

        nodejs = pkgs.nodejs_20;

        # Import the node environment generated by node2nix
        nodeEnv = import ./node-env.nix {
          inherit pkgs;
          inherit (pkgs) lib stdenv nodejs python3 libtool runCommand writeTextFile writeShellScript;
        };

        # Import your Node.js package using default.nix
        defaultPackage = import ./default.nix {
          inherit pkgs nodejs;
        };

      in rec {
        # Set up the development shell to include your Node.js package
        devShell = pkgs.mkShell {
          buildInputs = [ defaultPackage.package pkgs.nodejs ];
          # buildInputs = [ pkgs.nodejs_20 ];
        };
      }
    );
}

